#ifndef DBERROR_H
#define DBERROR_H

#define PAGE_SIZE 4096
typedef int RC;

RC RC_OK = 0;
RC RC_FILE_HANDLE_NOT_INIT = 1;
RC RC_FILE_NOT_FOUND = 2;
RC RC_FILE_INIT_FAILED = 3;
RC RC_FILE_READ_ERROR = 4;
RC RC_READ_NON_EXISTING_PAGE = 5;
RC RC_WRITE_FAILED = 6;
RC RC_WRITE_OUT_OF_BOUNDS_INDEX = 7;
RC RC_FILE_CLOSE_ERROR = 8;
RC RC_MALLOC_FAILED = 9;
RC RC_FILE_REMOVE_FAILED = 10;

void char *RC_message;

void printError(RC error);

#endif
